
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 78
#define YY_END_OF_BUFFER 79
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[192] =
    {   0,
        0,    0,    0,    0,    0,    0,   79,   77,   76,   66,
       69,    5,   49,   77,   58,   59,   47,   50,   57,   46,
       43,   48,   73,   73,   64,   65,   53,   51,   52,   74,
       74,   74,   74,   74,   74,   74,   62,   63,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   60,   77,   61,    3,    3,    3,   12,   12,   14,
       13,    6,   68,   73,   38,    0,    1,    4,    0,    0,
        0,    0,   56,   54,   55,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   39,   74,   74,   74,
       74,   74,   30,   74,   29,   74,   74,   74,   74,   74,

       74,   74,   74,   67,    3,    3,    2,   12,    7,   11,
       10,    8,    9,   40,    4,   75,   70,   71,   72,   74,
       74,   74,   74,   18,   74,   74,   74,   74,   74,   74,
       74,   28,   74,   74,   17,   42,   74,   74,   74,   74,
       74,   16,   74,   21,   74,   74,   74,   74,   74,   34,
       74,   32,   74,   74,   37,   74,   74,   74,   44,   74,
       24,   74,   74,   74,   22,   74,   36,   74,    0,   45,
       25,   74,   74,   74,   74,   27,   74,   23,   20,   74,
        0,   15,   26,   41,   33,   74,   35,   31,   74,   19,
        0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,    1,    1,   26,   27,   28,   29,   30,   31,
       32,   32,   33,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   34,   32,   32,   32,   32,   32,   32,   32,
       35,   36,   37,    1,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   32,   48,   49,   50,   51,
       52,   53,   32,   54,   55,   56,   57,   58,   59,   60,
       32,   32,   61,   62,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        4,    1,    1,    1,    1,    1,    5,    5,    5,    5,
        1,    1,    1,    1,    1,    5,    5,    5,    5,    5,
        5,    6,    6,    6,    1,    3,    1,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[200] =
    {   0,
        0,    0,   61,   62,   64,   72,  173,  881,  881,  881,
      881,  881,  881,  154,  881,  881,  881,   62,  881,   66,
      146,   60,   75,   84,  881,  881,  136,  126,  124,   92,
       99,  103,  111,  119,  123,  127,  881,  881,  135,  139,
      147,  152,  168,  177,  162,  191,  196,  212,  216,  223,
      227,  881,   72,  881,  130,  129,  110,    0,    0,  881,
      881,  212,  881,  234,  881,  110,  881,    0,  258,   51,
       70,    0,  881,  881,  881,    0,  239,  262,  266,  272,
      276,  280,  289,  298,  293,  302,  306,  313,  320,  332,
      336,  340,  344,  352,  358,  365,  369,  375,  380,  389,

      384,  393,  397,  881,  121,  111,  881,    0,  881,  881,
      881,  881,  881,  881,    0,  405,   79,   88,    0,  420,
      432,  436,  440,  444,  448,  453,  463,  470,  479,  483,
      493,  497,  501,  506,  510,  514,  519,  526,  532,  536,
      546,  550,  554,  560,  567,  576,  580,  590,  594,  598,
      602,  620,  609,  613,  626,  630,  634,  647,  651,  657,
      661,  668,  672,  676,  685,  689,  697,  703,   66,  707,
      711,  718,  722,  726,  730,  736,  740,  744,  748,  752,
       54,  762,  766,  770,  774,  780,  784,  881,  792,  796,
      881,  846,  852,  854,  860,  866,  872,   72,  874

    } ;

static yyconst flex_int16_t yy_def[200] =
    {   0,
      191,    1,  192,  192,  193,  193,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  194,
      194,  194,  194,  194,  194,  194,  191,  191,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  191,  191,  191,  195,  195,  191,  196,  196,  191,
      191,  191,  191,  191,  191,  191,  191,  197,  191,  191,
      191,  198,  191,  191,  191,  199,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,

      194,  194,  194,  191,  195,  195,  191,  196,  191,  191,
      191,  191,  191,  191,  197,  191,  191,  191,  198,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  191,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      191,  194,  194,  194,  194,  194,  194,  191,  194,  194,
        0,  191,  191,  191,  191,  191,  191,  191,  191

    } ;

static yyconst flex_int16_t yy_nxt[945] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   24,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   30,
       34,   30,   35,   36,   37,    8,   38,   30,   30,   39,
       40,   41,   42,   43,   30,   30,   44,   30,   45,   30,
       46,   30,   30,   47,   48,   49,   30,   50,   51,   30,
       52,   53,   54,   56,   56,   59,   60,  117,  117,   61,
       67,   57,   57,   59,   60,   68,  119,   61,   64,   64,
       64,   64,   64,   64,   64,   64,  118,  118,  118,   69,
       65,   64,   64,   64,   64,  117,  117,  188,   69,   62,

       64,   64,   64,   64,  118,  118,  118,   62,   76,   76,
       76,   76,  181,  106,   70,   76,   76,   76,   76,   76,
       76,   76,   76,  106,  114,  107,   71,   76,   76,   76,
       76,  106,  106,  104,   72,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   75,   79,   74,
       78,   76,   76,   76,   76,   76,   76,   76,   76,   73,
       66,   63,   80,   76,   76,   76,   76,   81,   76,   76,
       76,   76,  191,   82,  191,  191,  191,   85,   76,   76,
       76,   76,   83,  191,   76,   76,   76,   76,   84,   86,
      191,  191,  191,   76,   76,   76,   76,  191,   87,  191,

       88,  191,  191,  191,   96,   89,   90,   76,   76,   76,
       76,  191,   76,   76,   76,   76,  191,  109,  191,   91,
       93,  191,  191,  191,   92,  191,   94,   95,   76,   76,
       76,   76,   76,   76,   76,   76,  191,   97,   98,   76,
       76,   76,   76,   76,   76,   76,   76,  110,   69,  191,
       64,   64,   64,   64,   99,   76,   76,   76,   76,  191,
      191,  102,  111,  191,  191,  112,  191,  113,  191,  101,
      100,  116,  103,  191,  116,  116,  116,  116,   76,   76,
       76,   76,   76,   76,   76,   76,  191,  116,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,

      116,  191,  191,  191,  121,   76,   76,   76,   76,   76,
       76,   76,   76,  120,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,  191,  123,  122,   76,
       76,   76,   76,  191,  191,  124,   76,   76,   76,   76,
      126,  191,  125,  191,  191,  128,  191,  127,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,  191,  191,  191,  129,   76,   76,
       76,   76,  191,  130,   76,   76,   76,   76,  191,  191,
      131,   76,   76,   76,   76,   76,   76,   76,   76,  132,
      133,   76,   76,   76,   76,  191,   76,   76,   76,   76,

       76,   76,   76,   76,  134,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,  136,  116,  191,
      135,  116,  116,  116,  116,  191,  191,  137,  139,  191,
      138,  191,  191,  191,  116,  140,   76,   76,   76,   76,
      141,  191,  191,  143,  191,  191,  142,  116,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,  144,   76,
       76,   76,   76,  191,  191,  146,  191,  191,  147,   76,
       76,   76,   76,  191,  191,  145,   76,   76,   76,   76,
      191,  149,  191,  191,  148,   76,   76,   76,   76,   76,

       76,   76,   76,  191,  191,  150,  191,  191,  151,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,  152,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,  153,   76,   76,   76,   76,  191,
      191,  155,   76,   76,   76,   76,  191,  154,   76,   76,
       76,   76,   76,   76,   76,   76,  191,  156,  191,  191,
      191,  157,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,  191,  159,   76,   76,   76,   76,
      191,  191,  158,   76,   76,   76,   76,  191,  161,  191,
      191,  160,   76,   76,   76,   76,   76,   76,   76,   76,

      191,  191,  162,  191,  191,  163,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,  191,  169,  164,   76,   76,   76,   76,   76,
       76,   76,   76,  191,  191,  165,   76,   76,   76,   76,
      166,  167,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,  191,  171,  191,  191,  168,  191,
      191,  191,  170,   76,   76,   76,   76,   76,   76,   76,
       76,  191,  173,   76,   76,   76,   76,   76,   76,   76,
       76,  191,  191,  172,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,  191,  175,  191,  191,

      174,   76,   76,   76,   76,   76,   76,   76,   76,  191,
      176,  191,  177,   76,   76,   76,   76,  191,  178,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,  191,  191,  179,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
      191,  180,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,  191,  182,  191,  185,  184,  183,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,  191,  186,   76,   76,   76,   76,

       76,   76,   76,   76,  191,  191,  191,  187,   76,   76,
       76,   76,   76,   76,   76,   76,  191,  191,  191,  191,
      191,  191,  189,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  190,   55,   55,   55,   55,
       55,   55,   58,   58,   58,   58,   58,   58,   77,   77,
      105,  105,  105,  191,  105,  105,  108,  191,  191,  108,
      108,  108,  115,  191,  115,  115,  115,  115,   76,   76,
        7,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,

      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191
    } ;

static yyconst flex_int16_t yy_chk[945] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    5,    5,   70,   70,    5,
       22,    3,    4,    6,    6,   22,  198,    6,   18,   18,
       18,   18,   20,   20,   20,   20,   71,   71,   71,   23,
       20,   23,   23,   23,   23,  117,  117,  181,   24,    5,

       24,   24,   24,   24,  118,  118,  118,    6,   30,   30,
       30,   30,  169,  106,   23,   31,   31,   31,   31,   32,
       32,   32,   32,  105,   66,   57,   23,   33,   33,   33,
       33,   56,   55,   53,   23,   34,   34,   34,   34,   35,
       35,   35,   35,   36,   36,   36,   36,   29,   32,   28,
       31,   39,   39,   39,   39,   40,   40,   40,   40,   27,
       21,   14,   33,   41,   41,   41,   41,   34,   42,   42,
       42,   42,    7,   35,    0,    0,    0,   40,   45,   45,
       45,   45,   36,    0,   43,   43,   43,   43,   39,   41,
        0,    0,    0,   44,   44,   44,   44,    0,   41,    0,

       42,    0,    0,    0,   45,   42,   43,   46,   46,   46,
       46,    0,   47,   47,   47,   47,    0,   62,    0,   43,
       44,    0,    0,    0,   43,    0,   44,   44,   48,   48,
       48,   48,   49,   49,   49,   49,    0,   46,   47,   50,
       50,   50,   50,   51,   51,   51,   51,   62,   64,    0,
       64,   64,   64,   64,   48,   77,   77,   77,   77,    0,
        0,   50,   62,    0,    0,   62,    0,   62,    0,   49,
       48,   69,   51,    0,   69,   69,   69,   69,   78,   78,
       78,   78,   79,   79,   79,   79,    0,   69,   80,   80,
       80,   80,   81,   81,   81,   81,   82,   82,   82,   82,

       69,    0,    0,    0,   79,   83,   83,   83,   83,   85,
       85,   85,   85,   78,   84,   84,   84,   84,   86,   86,
       86,   86,   87,   87,   87,   87,    0,   81,   80,   88,
       88,   88,   88,    0,    0,   82,   89,   89,   89,   89,
       84,    0,   83,    0,    0,   86,    0,   85,   90,   90,
       90,   90,   91,   91,   91,   91,   92,   92,   92,   92,
       93,   93,   93,   93,    0,    0,    0,   88,   94,   94,
       94,   94,    0,   89,   95,   95,   95,   95,    0,    0,
       90,   96,   96,   96,   96,   97,   97,   97,   97,   91,
       92,   98,   98,   98,   98,    0,   99,   99,   99,   99,

      101,  101,  101,  101,   94,  100,  100,  100,  100,  102,
      102,  102,  102,  103,  103,  103,  103,   97,  116,    0,
       96,  116,  116,  116,  116,    0,    0,   98,   99,    0,
       98,    0,    0,    0,  116,  100,  120,  120,  120,  120,
      101,    0,    0,  103,    0,    0,  102,  116,  121,  121,
      121,  121,  122,  122,  122,  122,  123,  123,  123,  123,
      124,  124,  124,  124,  125,  125,  125,  125,  120,  126,
      126,  126,  126,    0,    0,  122,    0,    0,  123,  127,
      127,  127,  127,    0,    0,  121,  128,  128,  128,  128,
        0,  126,    0,    0,  125,  129,  129,  129,  129,  130,

      130,  130,  130,    0,    0,  127,    0,    0,  128,  131,
      131,  131,  131,  132,  132,  132,  132,  133,  133,  133,
      133,  129,  134,  134,  134,  134,  135,  135,  135,  135,
      136,  136,  136,  136,  130,  137,  137,  137,  137,    0,
        0,  133,  138,  138,  138,  138,    0,  131,  139,  139,
      139,  139,  140,  140,  140,  140,    0,  134,    0,    0,
        0,  137,  141,  141,  141,  141,  142,  142,  142,  142,
      143,  143,  143,  143,    0,  139,  144,  144,  144,  144,
        0,    0,  138,  145,  145,  145,  145,    0,  141,    0,
        0,  140,  146,  146,  146,  146,  147,  147,  147,  147,

        0,    0,  143,    0,    0,  145,  148,  148,  148,  148,
      149,  149,  149,  149,  150,  150,  150,  150,  151,  151,
      151,  151,    0,  152,  146,  153,  153,  153,  153,  154,
      154,  154,  154,    0,    0,  147,  152,  152,  152,  152,
      148,  149,  155,  155,  155,  155,  156,  156,  156,  156,
      157,  157,  157,  157,    0,  154,    0,    0,  151,    0,
        0,    0,  153,  158,  158,  158,  158,  159,  159,  159,
      159,    0,  157,  160,  160,  160,  160,  161,  161,  161,
      161,    0,    0,  156,  162,  162,  162,  162,  163,  163,
      163,  163,  164,  164,  164,  164,    0,  160,    0,    0,

      158,  165,  165,  165,  165,  166,  166,  166,  166,    0,
      162,    0,  163,  167,  167,  167,  167,    0,  164,  168,
      168,  168,  168,  170,  170,  170,  170,  171,  171,  171,
      171,    0,    0,  166,  172,  172,  172,  172,  173,  173,
      173,  173,  174,  174,  174,  174,  175,  175,  175,  175,
        0,  168,  176,  176,  176,  176,  177,  177,  177,  177,
      178,  178,  178,  178,  179,  179,  179,  179,  180,  180,
      180,  180,    0,  172,    0,  175,  174,  173,  182,  182,
      182,  182,  183,  183,  183,  183,  184,  184,  184,  184,
      185,  185,  185,  185,    0,  177,  186,  186,  186,  186,

      187,  187,  187,  187,    0,    0,    0,  180,  189,  189,
      189,  189,  190,  190,  190,  190,    0,    0,    0,    0,
        0,    0,  186,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  189,  192,  192,  192,  192,
      192,  192,  193,  193,  193,  193,  193,  193,  194,  194,
      195,  195,  195,    0,  195,  195,  196,    0,    0,  196,
      196,  196,  197,    0,  197,  197,  197,  197,  199,  199,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,

      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[79] =
    {   0,
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "swift.yy"
#line 2 "swift.yy"

    #include <stdio.h>
    #include <string.h>
    #include <unistd.h>
    #include <fcntl.h>
	#include <math.h>
	
    char strconst[1281] = {0};
	int convertOctalToDecimal(int octalNumber);
	int convertBinaryToDecimal(int n);	


#line 762 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define STRING 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 18 "swift.yy"


#line 949 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 192 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 881 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 20 "swift.yy"
{BEGIN(COMMENT); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 21 "swift.yy"
{printf("Found multiple line comment \n");  BEGIN(INITIAL);}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 22 "swift.yy"
{}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 23 "swift.yy"
{printf("Unterminated comment\n");return 0;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 25 "swift.yy"
printf("Found single line comment \n");
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 27 "swift.yy"
{ BEGIN(STRING); strcpy(strconst, ""); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 28 "swift.yy"
strcat(strconst, "\\");
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 29 "swift.yy"
strcat(strconst, "\"");
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 30 "swift.yy"
strcat(strconst, "\r");
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 31 "swift.yy"
strcat(strconst, "\t");
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 32 "swift.yy"
strcat(strconst, "\n");
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 33 "swift.yy"
strcat(strconst, "\\");
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 34 "swift.yy"
strcat(strconst,yytext);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 35 "swift.yy"
{
								printf("Found String: %s \n",strconst);
                                BEGIN(INITIAL);
                              }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 39 "swift.yy"
;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 41 "swift.yy"
printf("Found key word \"import\"\n");
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 43 "swift.yy"
printf("Found key word \"var\"\n");
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 44 "swift.yy"
printf("Found key word \"let\"\n");
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 46 "swift.yy"
printf("Found \"Int type\"\n");
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 47 "swift.yy"
printf("Found \"Char type\"\n");
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 48 "swift.yy"
printf("Found \"String type\"\n");
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 49 "swift.yy"
printf("Found \"Bool type\"\n");
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 50 "swift.yy"
printf("Found \"Float type\"\n");
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 51 "swift.yy"
printf("Found \"Double type\"\n");
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 53 "swift.yy"
printf("Found \"true\" constant\n");
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 54 "swift.yy"
printf("Found \"false\" constant\n");
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 56 "swift.yy"
printf("Found key word \"repeat\"\n");
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 57 "swift.yy"
printf("Found key word \"while\"\n");
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 59 "swift.yy"
printf("Found key word \"for\"\n");
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 60 "swift.yy"
printf("Found key word \"in\"\n");
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 62 "swift.yy"
printf("Found key word \"if\"\n");
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 63 "swift.yy"
printf("Found key word \"else if\"\n");
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 64 "swift.yy"
printf("Found key word \"else\"\n");
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 66 "swift.yy"
printf("Found \"switch\" \n");
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 67 "swift.yy"
printf("Found \"case\" \n");
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 68 "swift.yy"
printf("Found \"default\"\n");
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 69 "swift.yy"
printf("Found \"break\"\n");
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 72 "swift.yy"
printf("Found \"function\" (function declaration)\n");
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 73 "swift.yy"
printf("Found \"function type arrow\"\n");
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 75 "swift.yy"
printf("Found key word \"do\"\n");
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 76 "swift.yy"
printf("Found range word  \"...\"\n");
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 78 "swift.yy"
printf("Found key word \"return\"\n");
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 79 "swift.yy"
printf("Found key word \"nil\"\n");
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 81 "swift.yy"
printf("Found \".\"\n");
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 82 "swift.yy"
printf("Found \"self\" (like this pointer)");
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 83 "swift.yy"
printf("Found \"error\" call\n");
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 85 "swift.yy"
printf("Found \"-\"\n");
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 86 "swift.yy"
printf("Found \"*\"\n");
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 87 "swift.yy"
printf("Found \"/\"\n");
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 88 "swift.yy"
printf("Found \"%\"\n");
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 89 "swift.yy"
printf("Found \"+\"\n");
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 90 "swift.yy"
printf("Found \"=\"\n");
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 92 "swift.yy"
printf("Found \">\"\n");
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 93 "swift.yy"
printf("Found \"<\"\n");
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 94 "swift.yy"
printf("Found \"==\"\n");
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 95 "swift.yy"
printf("Found \"=>\"\n");
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 96 "swift.yy"
printf("Found \"<=\"\n");
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 98 "swift.yy"
printf("Found \",\"\n");
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 100 "swift.yy"
printf("Found \"(\"\n");
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 101 "swift.yy"
printf("Found \")\"\n");
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 102 "swift.yy"
printf("Found \"{\"\n");
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 103 "swift.yy"
printf("Found \"}\"\n");
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 104 "swift.yy"
printf("Found \"[\"\n");
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 105 "swift.yy"
printf("Found \"]\"\n");
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 106 "swift.yy"
printf("Found \":\"\n");
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 108 "swift.yy"
printf("Found \";\"\n");
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 109 "swift.yy"
printf("Found \"find new line symbol\"\n");
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 111 "swift.yy"
printf("Found \"or\"\n");
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 112 "swift.yy"
printf("Found \"and\"\n");
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 113 "swift.yy"
printf("Found \"not\"\n");
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 115 "swift.yy"
printf("Found binary: %d\n",convertBinaryToDecimal(atoi(yytext+2)));
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 116 "swift.yy"
printf("Found octal: %d\n",convertOctalToDecimal(atoi(yytext+2)));
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 117 "swift.yy"
printf("Found hexadecimal: %ld\n",strtol(yytext,NULL,16));
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 118 "swift.yy"
printf("Found decimal: %d\n",atoi(yytext));
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 119 "swift.yy"
printf("Found identifier: %s\n",yytext);
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 120 "swift.yy"
printf("Found double: %f\n",atof(yytext));
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
#line 122 "swift.yy"
{ printf("<<END OF FILE>>\n"); return 0; };
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
#line 124 "swift.yy"
;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 126 "swift.yy"
printf("Bad string %s\n", yytext);
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 127 "swift.yy"
ECHO;
	YY_BREAK
#line 1448 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 192 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 192 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 191);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 127 "swift.yy"


int main(int argc,char* argv[])
{
    if (argc > 1) 
    {
        yyin = fopen(argv[1], "r");
        yylex();
    }
    return 0;
}

int convertOctalToDecimal(int octalNumber)
{
    int decimalNumber = 0, i = 0;

    while(octalNumber != 0)
    {
        decimalNumber += (octalNumber%10) * pow(8,i);
        ++i;
        octalNumber/=10;
    }

    i = 1;

    return decimalNumber;
}

int convertBinaryToDecimal(int n)
{
    int decimalNumber = 0, i = 0, remainder;
    while (n!=0)
    {
        remainder = n%10;
        n /= 10;
        decimalNumber += remainder*pow(2,i);
        ++i;
    }
    return decimalNumber;
}



